workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PROJECT_DIR: "intelligent_mailbox_app"
    scripts:
      - name: Restore firebase_options.dart
      script: |
        echo "$FIREBASE_OPTIONS_DART" > lib/firebase_options.dart
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          flutter pub get
      - name: Build iOS
        script: |
          cd $PROJECT_DIR
          flutter build ios --release --no-codesign
    artifacts:
      - intelligent_mailbox_app/build/**/outputs/bundle/**/*.aab
