# Podfile

platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

install! 'cocoapods',
  :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
